### ISSUE TITLE
[Bug 1.2.9] 'Hidden' Tokens Display an Enormous Token Image for Players for Hidden Tokens

### ISSUE THREAD

**Issue by Red5MT** [EndlessFractal/yourTurn#10]
When a hidden token's turn starts, instead of a 'normal' size generic token image displayed over the ribbon, **_Your Turn!_** displays a token image that practically fills the screen. Below is an example, the GM screen on the left showing the token with Visibility toggled off and the player side on the right (its a wee bit large, no?).  ;)

![YourTurn](https://github.com/EndlessFractal/yourTurn/assets/83143296/c4adf7c9-9e38-488d-8117-fc4264154d5e)

I tested this running a GM window and PC window on the same PC (different browsers).

NOTE: I would also suggest that instead of a generic moster token for the 'hidden' image, you may want to use a question mark. It may be a custom event that uses a 'hidden' token instead of a monster.

**Comment by EndlessFractal** [comment]
This is what it happens when I don't properly unit test before releasing... *facepalm* 

It will be fixed in the next release.

> NOTE: I would also suggest that instead of a generic moster token for the 'hidden' image, you may want to use a question mark. It may be a custom event that uses a 'hidden' token instead of a monster.

I just found that image more visually appealing than a simple question mark.

Perhaps I could add in a feature to a named token "hiddenevent" and place another image for it...
https://game-icons.net/1x1/delapouite/perspective-dice-six-faces-random.html

Cheers!

**Comment by Red5MT** [comment]
> This is what it happens when I don't properly unit test before releasing... _facepalm_

Yeah, probably...    :)     It is a hobby though.

> I just found that image more visually appealing than a simple question mark.
> 
> Perhaps I could add in a feature to a named token "hiddenevent" and place another image for it... https://game-icons.net/1x1/delapouite/perspective-dice-six-faces-random.html

I dig the die too. Just thought I would throw out my opinion. It's your module for your game...and you were nice enough to share it...not gonna complain here.  :)   Honestly, I am surprised that Ripper has not added this functionality to Combat Carousel Tracker. Your Turn and CCT are a pretty good combo.

**Comment by Red5MT** [comment]
I assume you will see this comment even though the thread is closed.

First, tested and looks good. I am happy to be able to add this back into my game.
Second, as a minor visual improvement, might I suggest making the 'hidden' token image a wee bit larger to be more consistant with the sizes of other tokens. See the image below:
![YourTurnTokenSize](https://github.com/EndlessFractal/yourTurn/assets/83143296/183eef7a-0104-4c7c-ad51-f201e00f4bc0)
