### ISSUE TITLE
[Feature Request] Ability to disable "Next Up" part of message

### ISSUE THREAD

**Issue by MNielson** [EndlessFractal/yourTurn#3]
-The ability to disable "Next Up...." in settings.

Certain games, like those with popcorn initiative such as Exalted, do not have a fixed known "next character". 
A flag to disable the "Next Up" part of the message would be greatly appreciated for such systems.

After any characters turn, it is *that characters* choice, who comes next. (Other systems may use other methods that also don't rely on initiative value alone).
As such, the "next character" is not known until the end of the previous characters turn.
![image](https://github.com/EndlessFractal/yourTurn/assets/23503856/fa36063c-ba40-4bac-8ebe-64b7d5ac3d3c)

**Comment by EndlessFractal** [comment]
So, the players themselves decide who goes next. 
The player that goes next, clicks on some button and banner should be shown.

Is that correct?

**Comment by MNielson** [comment]
Either the currently active player or the GM decides who goes next by clicking the button next to the player that goes next.
When the button next to player X is clicked, the banner showing "Player X's turn" should be shown.

**Comment by Red5MT** [comment]
@EndlessFractal - any chance you might be able to add this feature to your fork? Displaying the 'Next Up' on a hidden enemy a turn ahead of time does kind of spoil the surprise a bit.

**Comment by EndlessFractal** [comment]
> @EndlessFractal - any chance you might be able to add this feature to your fork? Displaying the 'Next Up' on a hidden enemy a turn ahead of time does kind of spoil the surprise a bit.

Added in the latest release!
