### ISSUE TITLE
Your Turn dando Erro na V11.

### ISSUE THREAD

**Issue by PilotodeMouse** [EndlessFractal/yourTurn#4]
![image](https://github.com/EndlessFractal/yourTurn/assets/76591455/d61b999a-5fa5-4cbb-b4f7-da8b91b5d483)

Simplesmente não consigo instalar o YourTurn do seu update! :( 
Por gentileza ne ensine o caminho para essa Missão! 🗡️

**Comment by EndlessFractal** [comment]
Olá!
É esse link que está utilizando para instalar o módulo?
> https://github.com/EndlessFractal/yourTurn/releases/download/latest/module.json

Testei aqui e está funcionando corretamente.

**Comment by PilotodeMouse** [comment]
![image](https://github.com/EndlessFractal/yourTurn/assets/76591455/0075b463-c047-4626-b476-0d8318b40457)
 Agora instalei corretamente mestre!
 Mas deu erro mesmo assim, conforme a imagem acima!

**Comment by EndlessFractal** [comment]
Infelismente é um problema conhecido e ainda estou tentando encontrar uma solução.

> https://github.com/Autmor/yourTurn/issues/20

Vou fechar aqui para direcionar para o tópico principal.
