### ISSUE TITLE
Next Up Names Actors Marked Defeated in Tracker

### ISSUE THREAD

**Issue by Armandeus66** [EndlessFractal/yourTurn#7]
The "next up" announcement names an actor next in initiative order even if it is marked "defeated" (=dead).

I think It might be better if defeated actors were skipped, and the next actor in initiative order that is active in the tracker was named instead.

Versions:
module 1.2.6
Foundry 11.315
Pathfinder 2E system 5.13.2

**Comment by EndlessFractal** [comment]
Fixed in the latest release!
