### ISSUE TITLE
v1.2.8: Turn Change Notifications Disabled for Player Actors

### ISSUE THREAD

**Issue by Red5MT** [EndlessFractal/yourTurn#8]
Just upgraded from 1.2.6 to 1.2.8 today. It appears that the turn notifications are not displayed for Player Actors. They do trigger for Non-Player Actors.

DnD 5e 2.4.1
Foundry 11.315
Windows 11 Server
Windows 10 / Chrome Client

After discovering the issue in my main world, I created a new world with just Your Turn! enabled. 
I disabled the new 'Hide' options.
I then grabbed some monsters from the 5e compendium and tested. Your Turn! worked fine. 
I then created a new PC Actor. The Your Turn! notification did not display for the PC.
I then created a new Non-Player Actor (with no additional changes). The Your Turn! notification was displayed.
I also ran through the same tests with new 'Hide' options enabled. No change.

Reverting back to 1.2.6 does fix the issue immediately.

NOTE: The new 'Hide' feature DOES appear to be working for NPC Tokens.

PS: Thank you for the feature update. I certainly appreciate it. Sorry to have to report this issue.

**Comment by EndlessFractal** [comment]
Hello! Thank you for your interest and for your comprehensive bug report.

I've pinpointed the issue. It's not properly handling if a token does not have a texture. I'll check what I can do to fix it.

Cheers!
