### ISSUE TITLE
[Feature Request]: Option for Shorter Notifications

### ISSUE THREAD

**Issue by Red5MT** [EndlessFractal/yourTurn#9]
This is MY ADHD kicking in.   :)

I sometimes feel the duration of the notifications are a bit long (around 8 seconds start to finish). They do cover a fair bit of real estate on the screen, so they do get in the way when players are paying attention and want to get their turn going.

My suggestion (if not too difficult) would be to provide a setting in the options for a shorter display. When enabled, as soon as the ribbon touches the right side of the screen, the ribbon does not rewind. Instead, then token image and ribbon quickly fade out. 4 seconds feel right to me, but you make the call.

**Comment by EndlessFractal** [comment]
Thanks for your suggestion! I'll add it to my roadmap!
